### ISSUE TITLE
Animal form improvements

### ISSUE THREAD

**Issue by bbimber** [bimberlabinternal/BimberLabKeyModules#22]
@hextraza A few things I noticed on the form:

- Can we make it such that when the user clicks on the radio label, it also selects the radio? this is nicer than making them click on just the radio dot
- Could the required/missing fields turn red on submit or give another visual queue on what's missing?
- When you hit submit without entering fields, it scrolls to the first field, but there's no alert or other indication on what the problem is. What would making a popup saying something like 'One or more required fields is missing'?
- Can you remove the 'not started' option from the IACUC approval dropdown?
- Good job making the 'number of animals' field numeric, but I was able to pick 12.4 (should be integers)
- If I understand this, the default text inside each textarea is basically the field's label? What about putting this above the text area, so it's not lost once the user enters something?
- I have good eyes, but the font size within the textareas is probably too small for most people.
- I like the question mark popup; however, when i load this on chrome, the popup centers on the ?. The problem is that long text is cut off on the left side of the screen.

**Comment by bbimber** [comment]
Also the 'Animal Facilities and Capabilities' isnt intuitive to me. Maybe this is how the spec wrote it, but it looks more like one group of 4 radios rather than 2 pairs. Maybe we should just make those into 2 dropdowns with 2 options/ea?

**Comment by hextraza** [comment]
Did you test everything on Chrome? It should scroll to the relevant input and there should be a pop-up telling you that you forgot to fill-in one of the fields.

Agreed on the other design issues. I can also repro the weird centering bug on the question mark popover.

**Comment by bbimber** [comment]
Yes, I was using chrome for it all. Regarding submitting a form missing fields: I tried to submit a totally blank form. When I did this, it scrolled to the first field, which it probably what you expect. I was also able to see the 'please fill out this field' thing, but at least on my chrome instance it tries to auto-fill, so that yellow alert isnt visible:

![image](https://user-images.githubusercontent.com/7724863/129298198-15566a16-fc97-414f-b851-a1969181e4df.png)
